@extends('layout')

@section('page-content')
    <br>
    <br>
    <h1 class="text-center text-primary">Welcome to Employee information System</h1>
    <h2 class="text-center font-bold ">Generated By Md. Nadim Mir</h2>
   
    <a class="" href="/employees"> <button>Show All Employee Data</button></a>
    
@endsection
